# Generated by Django 3.1.3 on 2021-08-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reference_input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_input', to='check.satellite')),
            ],
        ),
        migrations.CreateModel(
            name='pids_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid_number', models.PositiveIntegerField(default=1000)),
                ('pid_status', models.CharField(max_length=50)),
                ('mnemonic', models.CharField(max_length=50)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pids_status', to='check.reference_input')),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pids_status', to='check.satellite')),
            ],
        ),
    ]
